services:
  - type: web
    name: job-portal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && mkdir -p uploads static/css static/js templates
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: job-portal-db
          property: connectionString
      - key: DATABASE_NAME
        value: job_portal
      - key: DEBUG
        value: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 1440
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: LOG_LEVEL
        value: INFO

databases:
  - name: job-portal-db
    databaseName: job_portal
    user: jobportal_user
    plan: free
